---
title: "STDA-project"
output:
  pdf_document: default
  html_document: default
---


```{r}
require(zoo)
require(xts)
data <- read.csv("sims2018milan.csv",sep = ";")
data <- rbind(data, read.csv("foreignsim_2019-11-07.csv",sep = ";"))

data$prefix <- NULL
data$country <- NULL
data$num <- NULL
data$total.ita.sim <- NULL
```



```{r}
ll <- aggregate.data.frame(data$total.foreign.sim,by=list(data$date),FUN=mean)
names(ll)[2] <- "total.foreign.sim"
names(ll)[1] <- "Date"
data <- ll

dim(data)
data <- data[-c(656,657,658), ]
dim(data)

print("minimum, lower-hinge, median, upper-hinge, maximum)")
fivenum(data$total.foreign.sim)
hist(data$total.foreign.sim)
```


```{r}
data$Date <- as.Date(data$Date, format = "%Y-%m-%d")
#typeof(data$date[1])
data.xts <- xts(data$total.foreign.sim, order.by=data$Date, frequency = 365)
data.ts <- ts(data$total.foreign.sim)

main <- "foreign sim per day"
ylab<-"Tot of sim in that day"
plot(data.xts,ylab=ylab,main=main)
```


```{r}
tt<-as.numeric(time(data.ts))
fit2<-lm(data.ts~poly(tt,degree=2,raw=TRUE))
fit4<-lm(data.ts~poly(tt,degree=4,raw=TRUE))
```



```{r}
main <- "foreign sim per day"
plot(data.ts,ylab=ylab,main=main)
lines(tt,predict(fit2),col='red',lwd=2)
lines(tt,predict(fit4),col='blue',lwd=2)
legend("bottomright",legend = c("2nd order","4th order"),lwd=2,lty=1,col=c("red","blue"))
```



```{r}
data.xts.log <- xts(sqrt(data$total.foreign.sim), order.by=data$Date, frequency = 365)

main <- "foreign sim per day"
ylab<-"Tot of sim in that day"
plot(data.xts.log,ylab=ylab,main=main)
```

# Decomposing non seasonal data

```{r}
require(TTR)
data.ts.ma <- SMA(data.ts, n=5)
plot.ts(data.ts.ma)
```


```{r}
# Decomposing seasonal data
#data.ts.dec <- decompose(data.ts)
#plot.ts(data.ts.dec)
#Error in decompose(data.ts) : time series has no or less than 2 periods
# so no seasonality ca be fou d by R
```


```{r}
#install.packages("forecast")
library(forecast)
trend.data = ma(data.ts, order = 12, centre = T)
plot(data.ts)
lines(trend.data, col="red")
```

# acf & pacf

```{r}
acf(data.ts, 40)
```

Every 7 lags the peak recurs

```{r}
# Part (c)
t = time(data.ts) 
FIT = lm(data.ts ~ t) 
summary(FIT)
```

```{r}
X = as.vector(time(data.ts))
plot(X, data.ts, xlab = "Year", ylab = "CO2 Level", type = "l") 
abline(FIT)
```


```{r}
require(TSA)
RES = rstudent(FIT)
plot(X, RES, xlab = "Year", ylab = "Standardized Residuals", type = "l") 
points(X, RES)
```

```{r}
acf(RES, main = "Standardized Residuals", 36)
```


```{r}
pacf(data.ts)
```



# Detrending


```{r}
require(pracma)
#detrend.data = data.ts - trend.data
detrend.data = detrend(as.matrix(data.ts), 'linear', 5)
plot(data.ts)
lines(data.ts - detrend.data, col="red")
```

# Finding seasonality

```{r}
m_data = t(matrix(data = detrend.data, nrow = 4))
seasonal.data = colMeans(m_data, na.rm = T)
plot(as.ts(rep(seasonal.data,16)))
```

# the rest is residuals

```{r}
random.data = data.ts - trend.data - seasonal.data
plot(random.data)
```

```{r}
Box.test(random.data, lag=10, fitdf=0)
```


```{r}
Box.test(random.data, lag=10, fitdf=0, type="Lj")
```

There is strong evidence that data is non stationary but im not able to decompose the seasonality

```{r}
checkresiduals(naive(random.data))
```


# trying to fix

```{r}
library(pracma)
data.ts.box <- BoxCox(data.ts,lambda=0.3)
data.ts <- data.ts.box
SP.hampel <- hampel(data.ts, 5, 3)
SP.hampel$ind

SP.hampel.outlier.times <- vector()
SP.hampel.outlier.values <- vector()
i <- 1
for (ind in SP.hampel$ind) {
    SP.hampel.outlier.times[i] <- time(data.ts)[ind]
    SP.hampel.outlier.values[i] <- data.ts[ind]
    i <- i + 1
}
options(repr.plot.width=8, repr.plot.height=4)
plot(data.ts, col="dodgerblue2")
points(SP.hampel.outlier.times, SP.hampel.outlier.values,
    pch=4, col="red")
grid()
```


```{r}
plot(data.ts, lwd=1.5, col="red")
lines(SP.hampel$y, lwd=1.5, col="dodgerblue2")
```


```{r}
data.ts.out <- ts(SP.hampel$y)
plot(data.ts.out)
data.ts <- data.ts.out
```



```{r}
require(fpp)
# data.ts.box <- BoxCox(data.ts,lambda=0.4)
fit <- Arima(data.ts.box, order=c(3,1,3))
summary(fit)
```

```{r}
checkresiduals(fit)
```

```{r}
autoplot(forecast(fit))

```



```{r}
tseries_lf5 <- filter(data.ts, filter = rep(1/5, 5), sides = 1)
plot.ts(cbind(data.ts, tseries_lf5), plot.type = 'single', col = c('black', 'red'))
```

